
### Send Confirm Recipes POST request with json body
### Amazon.DynamoDBv2.AmazonDynamoDBException: The provided key element does not match the schema
POST https://yp5w6dttraoriw22lcv4hmukoi0lxopx.lambda-url.eu-west-2.on.aws/recipes/confirm
Content-Type: application/json

{
  "RecipeIds": [
    "3f54091d-dbc2-4ff8-a7eb-3e18bbf18ec5"
  ]
}

### Get Latest
### Amazon.DynamoDBv2.AmazonDynamoDBException: The provided key element does not match the schema
GET https://yp5w6dttraoriw22lcv4hmukoi0lxopx.lambda-url.eu-west-2.on.aws/recipes/latest
Content-Type: application/json


### Migrate Data
### Amazon.DynamoDBv2.AmazonDynamoDBException: The provided key element does not match the schema
GET https://yp5w6dttraoriw22lcv4hmukoi0lxopx.lambda-url.eu-west-2.on.aws/recipes/migrate
Content-Type: application/json